/* eslint-disable */
// AUTO-GENERATED by scripts/generate-changelog.mjs — do not edit by hand.
// Refresh with: pnpm --filter @coursewise/web changelog

export interface RawCommit {
  hash: string;
  dateISO: string;
  subject: string;
}

export const REPO_URL: string | null = "https://github.com/lastcow/CourseWise";

export const RAW_COMMITS: RawCommit[] = [
  {
    "hash": "35a6877cdaa33099198fe2b5edc4d03536416377",
    "dateISO": "2026-05-27T15:47:12-04:00",
    "subject": "Roster: richer password-reset dialogs (student info, expiry, color) (#197)"
  },
  {
    "hash": "246c0d1340103f5b1d63c9cd107f9d893d36d31d",
    "dateISO": "2026-05-27T15:40:45-04:00",
    "subject": "Student Modules: add 'to do & upcoming' status panel (#196)"
  },
  {
    "hash": "6c8b9ec971c43096a259243cc7a57fe723af5d00",
    "dateISO": "2026-05-27T15:25:12-04:00",
    "subject": "Roster: confirm before sending a student password reset link (#195)"
  },
  {
    "hash": "55b1f0ae2ec9a428fd5a176092982bfb56c1ca90",
    "dateISO": "2026-05-27T15:13:06-04:00",
    "subject": "Password reset: self-service + admin/teacher-initiated (#194)"
  },
  {
    "hash": "6df2ed6152b6f0b94dac17e0ae4062da051ac95e",
    "dateISO": "2026-05-27T03:31:45-04:00",
    "subject": "Fix: group submit no longer 409s \"conflict with another change\" (#193)"
  },
  {
    "hash": "09d55edaade200b12a4818a11aa28f42362c0737",
    "dateISO": "2026-05-27T02:40:22-04:00",
    "subject": "Submissions: multiple files + visible \"what I submitted\" (#192)"
  },
  {
    "hash": "6c13987a567931780fefc970f952b2e2124236ef",
    "dateISO": "2026-05-27T02:12:26-04:00",
    "subject": "Submissions: grade group assignments as one unit (#191)"
  },
  {
    "hash": "972da120d878061815c754305cc81b612ae52f65",
    "dateISO": "2026-05-27T01:22:23-04:00",
    "subject": "Modules: per-item pending tasks instead of aggregate counts (#190)"
  },
  {
    "hash": "07f3175a9be0d65d5542bdb5695bdafa4e69e4e2",
    "dateISO": "2026-05-26T00:39:34-04:00",
    "subject": "Fix: language menu background renders transparent (#189)"
  },
  {
    "hash": "9c8324c5442ab2e6df4a3d2f2e120caadfebc5d6",
    "dateISO": "2026-05-26T00:29:04-04:00",
    "subject": "Add French locale + click-to-open language picker (#188)"
  },
  {
    "hash": "0f711d391f156dabc78bd6d0db8219be001448a3",
    "dateISO": "2026-05-26T00:14:42-04:00",
    "subject": "i18n: localize ContactPage + DataRequests form UI (#187)"
  },
  {
    "hash": "5a296028855157f65564698478e938c1879eef95",
    "dateISO": "2026-05-25T23:08:35-04:00",
    "subject": "Alerts: group by student by default (#186)"
  },
  {
    "hash": "1119586e3ae55954bbb5fa9e098203541580f7b4",
    "dateISO": "2026-05-25T22:57:47-04:00",
    "subject": "Teacher Alerts: collapsible rows + type filter + course scope note (#185)"
  },
  {
    "hash": "489d7d971bdb010a081cd00dd7a56f1943dcbdac",
    "dateISO": "2026-05-25T19:53:22-04:00",
    "subject": "Attendance: let teachers edit records on closed sessions (#184)"
  },
  {
    "hash": "41b0e623698a0622de3eef20b5c64b48bca04c3f",
    "dateISO": "2026-05-25T18:06:37-04:00",
    "subject": "Disable Generate-with-AI button on course Overview (#183)"
  },
  {
    "hash": "b964f33b02175837d786818773857bd292883a67",
    "dateISO": "2026-05-25T16:09:38-04:00",
    "subject": "Attendance: default to absent; drop the Pending state + filter (#182)"
  },
  {
    "hash": "10e9ed13dbfa3bbcaa617649faeb360344ca1e70",
    "dateISO": "2026-05-25T15:52:09-04:00",
    "subject": "Attendance: clickable status chips filter the roster (#181)"
  },
  {
    "hash": "5dff7e0ba13d14f44b8130ea6fbd2eecf5ff1057",
    "dateISO": "2026-05-25T15:49:35-04:00",
    "subject": "Attendance: real confirm dialog for delete-session (#180)"
  },
  {
    "hash": "de23781107ff3319d3184d0b27cd353b26a543e4",
    "dateISO": "2026-05-25T15:36:19-04:00",
    "subject": "Attendance: pending default + chronological session order (#179)"
  },
  {
    "hash": "41edf1c4df11685c6358bc824cbc0338459252c1",
    "dateISO": "2026-05-25T14:50:20-04:00",
    "subject": "Invitations: show \"Expired\" once expiresAt has passed (#178)"
  },
  {
    "hash": "9910e57d2ee1cc7664711511f803131d971a3a90",
    "dateISO": "2026-05-25T14:42:46-04:00",
    "subject": "Wire capacity hint into TeacherGroupSetsPage too (#177)"
  },
  {
    "hash": "d982712451e45e3ba24ec3eaab648759b2f0ed35",
    "dateISO": "2026-05-25T14:31:38-04:00",
    "subject": "Group-set dialogs: real-time capacity hint (#176)"
  },
  {
    "hash": "0949440dd6545a7dee5f109ae47546af85d3c5de",
    "dateISO": "2026-05-25T14:29:20-04:00",
    "subject": "SideNav: count badges on more per-course items (#175)"
  },
  {
    "hash": "5e2026a9ba6bf345e4ace2e9c123ce4a73381a25",
    "dateISO": "2026-05-25T14:25:45-04:00",
    "subject": "SideNav: outlined-square badge with active-students count (#174)"
  },
  {
    "hash": "a2f9d7f019c67a80da7516e9d7d96375043aa9fc",
    "dateISO": "2026-05-25T14:20:41-04:00",
    "subject": "Fix: each group's assign picker owns its own selection (#173)"
  },
  {
    "hash": "2e82c1a680e0d2eef796f26ed180b00432ff22f6",
    "dateISO": "2026-05-25T14:16:07-04:00",
    "subject": "Students page: collapsible groups in the grouped view (#172)"
  },
  {
    "hash": "1e3b392a246ccba888ccbad674466408af2257b3",
    "dateISO": "2026-05-25T14:10:11-04:00",
    "subject": "Group-set resize + per-group capacity override (#171)"
  },
  {
    "hash": "1c1a6f5ca82587333bff9163f8548c81e6efbaf1",
    "dateISO": "2026-05-25T13:47:51-04:00",
    "subject": "Attendance: redesign roster section (compact, professional) (#170)"
  },
  {
    "hash": "cf0cfe0aaf7d82fa72d6e5b91bd992be08ddb11a",
    "dateISO": "2026-05-25T11:26:43-04:00",
    "subject": "Student account hard-delete (admin + teacher) (#169)"
  },
  {
    "hash": "cfe79e694f6d76bb0e54dead1e24e71f011271aa",
    "dateISO": "2026-05-24T21:49:04-04:00",
    "subject": "Merge x/y count into the view-submissions button itself (#168)"
  },
  {
    "hash": "70911f362c02858d7e29718c6dda41d7cda3f0bc",
    "dateISO": "2026-05-24T21:42:45-04:00",
    "subject": "Match submission badge height to action icon (h-8) (#167)"
  },
  {
    "hash": "5b6e6a42025b620da6b7bc3a964f3044857f92ca",
    "dateISO": "2026-05-24T15:29:05-04:00",
    "subject": "Fix Assignments submission count: exclude drafts, dedupe by group (#166)"
  },
  {
    "hash": "15f8191a821e3ce8cd9cf7514f9b9893fc3fface",
    "dateISO": "2026-05-24T15:16:24-04:00",
    "subject": "Split-pill ungraded/total badge next to view-submissions icon (#165)"
  },
  {
    "hash": "b91093e5c59b2e26253c6765b2000b5b45856fed",
    "dateISO": "2026-05-24T15:05:49-04:00",
    "subject": "Outline ungraded/total badge on Assignments view-submissions action (#164)"
  },
  {
    "hash": "f4ae9bb5163ec59994716bcc67a3d4fb1d12869f",
    "dateISO": "2026-05-24T14:47:45-04:00",
    "subject": "Remove API tokens link from top nav (#163)"
  },
  {
    "hash": "802a7121bc9a2703ca088b473374ee39d495487e",
    "dateISO": "2026-05-24T14:35:36-04:00",
    "subject": "Add Modify-student dialog to Students page (name + student#) (#162)"
  },
  {
    "hash": "4da66ecfe8d364f2054d69a0c5dd700b5b32c4c9",
    "dateISO": "2026-05-24T14:27:26-04:00",
    "subject": "Fix Stay-signed-in race that logged the user out anyway (#161)"
  },
  {
    "hash": "fb799346ccdcd428c6b6cbba178541e5db6555d4",
    "dateISO": "2026-05-24T13:30:53-04:00",
    "subject": "Onsite messaging V1 (#160)"
  },
  {
    "hash": "e333b1162bde4b17298836660220bed5c0186471",
    "dateISO": "2026-05-24T12:54:58-04:00",
    "subject": "Add client-side pagination to Students roster (teacher + student) (#159)"
  },
  {
    "hash": "192ab43d5dc90ee8ce6f8ef8f2b32ab485b4720e",
    "dateISO": "2026-05-23T16:27:02-04:00",
    "subject": "Pending tasks: hide zero-count cards, collapse to All Caught Up (#158)"
  },
  {
    "hash": "f7e51e6720f00d95d92020f7b64c8f405f4d64c3",
    "dateISO": "2026-05-23T16:13:29-04:00",
    "subject": "Teacher Modules: pending-tasks sidebar (ungraded counts) (#157)"
  },
  {
    "hash": "aa143812a00544959705930820746d09611eeb4d",
    "dateISO": "2026-05-23T15:02:59-04:00",
    "subject": "Student Course overview: mirror teacher layout with per-card counts (#156)"
  },
  {
    "hash": "2bc69bbe94710fffb3ede539fa4512a53a0ef1e4",
    "dateISO": "2026-05-23T13:52:30-04:00",
    "subject": "Materials download: revert to .md (drop jspdf) (#155)"
  },
  {
    "hash": "7606c09db78009c2ed7dee3708d4914bfc04b1ee",
    "dateISO": "2026-05-23T13:32:05-04:00",
    "subject": "Materials download: emit PDF instead of markdown (#154)"
  },
  {
    "hash": "32b9d7d4df915c4babc4df9ae12e602833c02dd8",
    "dateISO": "2026-05-23T13:23:35-04:00",
    "subject": "Materials pages: attached toolbar + per-row download (#153)"
  },
  {
    "hash": "e8300f82238d965ba2253c6582e608debd5b40e1",
    "dateISO": "2026-05-23T12:30:51-04:00",
    "subject": "Allow students to download files attached to published presentations (#152)"
  },
  {
    "hash": "c4cb3d2c28fffe11a8b9a0fede66ffe80f669dfd",
    "dateISO": "2026-05-23T12:24:20-04:00",
    "subject": "Show download button on student Presentations page when file is available (#151)"
  },
  {
    "hash": "ee25b099a52c8bcb233087d11272bed6bf19d841",
    "dateISO": "2026-05-23T12:19:34-04:00",
    "subject": "Reading materials page: switch to single-table layout for both roles (#150)"
  },
  {
    "hash": "780df6ceb75af5ea483abe97f5a6b589be06a982",
    "dateISO": "2026-05-23T12:15:06-04:00",
    "subject": "Show \"not yet open\" message on student assignment submission (#149)"
  },
  {
    "hash": "6e5a07a0e893bf7497e1520befee32fb4981f7c3",
    "dateISO": "2026-05-23T12:04:52-04:00",
    "subject": "Syllabus: keep Upcoming window fresh with a useNow tick (#148)"
  },
  {
    "hash": "27012feec0393980b7b09938ec23c1137d4e7624",
    "dateISO": "2026-05-23T11:57:39-04:00",
    "subject": "Accordion: primary-color left strip when an item is open (#147)"
  },
  {
    "hash": "776b0b3e407b4036171d0f39daa82dbeae3046b0",
    "dateISO": "2026-05-23T11:46:04-04:00",
    "subject": "Modules: merge Expand all / Collapse all into one toggle button (#146)"
  },
  {
    "hash": "9dfbce2fa5645f06ea89c6db9c7f9b6a2ae68e2c",
    "dateISO": "2026-05-23T11:23:21-04:00",
    "subject": "Modules: Expand all / Collapse all buttons (#145)"
  },
  {
    "hash": "6837bf22e80b0a5e3c9dfeacfa80b460cc22827f",
    "dateISO": "2026-05-23T11:20:13-04:00",
    "subject": "Modules: remove up/down arrow buttons (drag-and-drop replaces them) (#144)"
  },
  {
    "hash": "01067110c8cf02d62810abe01b0f51548bc962c0",
    "dateISO": "2026-05-23T11:15:04-04:00",
    "subject": "SideNav: swap Modules and Syllabus order (#143)"
  },
  {
    "hash": "7c57f1496d32dcf608931f1edf8bf4d8bea03afc",
    "dateISO": "2026-05-23T11:07:15-04:00",
    "subject": "Syllabus page (V1) (#142)"
  },
  {
    "hash": "189977d1e95e88f78b517214f7e6e9b4384ed114",
    "dateISO": "2026-05-23T10:38:36-04:00",
    "subject": "Accordion: leading slot + solid disclosure triangle (#141)"
  },
  {
    "hash": "e1cde931081a2eebbf3d6e61a0c2ab3166dd60c1",
    "dateISO": "2026-05-23T10:27:58-04:00",
    "subject": "Modules: drag-and-drop module reordering (#140)"
  },
  {
    "hash": "2fe6948f5ad24674d27b323dcc6f37796e7a1a90",
    "dateISO": "2026-05-23T10:13:05-04:00",
    "subject": "Topnav: show \"CODE – Name\" center label for the active course (#139)"
  },
  {
    "hash": "36ca1ce2494abe540c80268c070887288b344e4f",
    "dateISO": "2026-05-23T10:04:25-04:00",
    "subject": "SideNav: append course code to \"Current course\" group title (#138)"
  },
  {
    "hash": "c3c9b661fd9a081f63bafcd0e248bdb71c64d255",
    "dateISO": "2026-05-23T00:47:06-04:00",
    "subject": "Invitations: surface a shareable /invite/CODE link per code (#137)"
  },
  {
    "hash": "ebff43dd503c7ba8f8bcfe06dbd3f73f588d4198",
    "dateISO": "2026-05-23T00:36:22-04:00",
    "subject": "Modules: download button on materials + assignments (#136)"
  },
  {
    "hash": "3eab82f9ec14f6de13af872aab7ad9ffb12d9dac",
    "dateISO": "2026-05-23T00:20:19-04:00",
    "subject": "Modules: open-in-Gamma icon link before download (#135)"
  },
  {
    "hash": "1db50986a6e73b89760dd3394e30446758288e4e",
    "dateISO": "2026-05-23T00:15:17-04:00",
    "subject": "Modules: wrap each subsection in its own card (#134)"
  },
  {
    "hash": "c5b72108c9c69b5b507dc2aedf45f6425660c3e7",
    "dateISO": "2026-05-23T00:12:04-04:00",
    "subject": "Presentations: download button for any file-backed row (#133)"
  },
  {
    "hash": "5b11348d8385a5121373d988656efa9cab50f79e",
    "dateISO": "2026-05-22T23:54:26-04:00",
    "subject": "Presentations: upload a PPTX/PDF/etc and link to module (#132)"
  },
  {
    "hash": "afc602e93a0e3977016c962b56db0fd97b2d3104",
    "dateISO": "2026-05-22T23:46:47-04:00",
    "subject": "Gamma: reading materials start unchecked (#131)"
  },
  {
    "hash": "88405a99a4652ca53fce7f278a162087843fc3b9",
    "dateISO": "2026-05-22T23:36:18-04:00",
    "subject": "Home: drop \"Trusted by [placeholder institutions]\" line (#130)"
  },
  {
    "hash": "8bc5b7e07ceead0f02567e5b846ab5beafcec122",
    "dateISO": "2026-05-22T03:15:48-04:00",
    "subject": "Course cards redesign with banner + counts (#129)"
  },
  {
    "hash": "8e0b8c1caf7512932f6963dfbba6f96803832260",
    "dateISO": "2026-05-22T02:47:28-04:00",
    "subject": "Design: course cards redesign with banner image + counts (#128)"
  },
  {
    "hash": "7000e4f094e1c3438bd2212bce96f7e3e2bd31f5",
    "dateISO": "2026-05-22T02:04:46-04:00",
    "subject": "Fix: accept both POST and PATCH on submission grade + return (#127)"
  },
  {
    "hash": "5f076b3e2c7c62ec9c444cdb1e1d73d4575e01f6",
    "dateISO": "2026-05-22T00:04:59-04:00",
    "subject": "Teacher assignments list: ungraded badge on view-submissions icon (#126)"
  },
  {
    "hash": "fb7ddc030f92e2dbc481c086b96b7355e1833270",
    "dateISO": "2026-05-21T23:48:50-04:00",
    "subject": "Teacher course overview: \"Needs grading\" card with per-surface tiles (#125)"
  },
  {
    "hash": "aed24089fe3764a6fff04059f8bb539ccfc94700",
    "dateISO": "2026-05-21T23:43:00-04:00",
    "subject": "Teacher attendance: surface true status when records load (#124)"
  },
  {
    "hash": "9630ea068b5dfe1c3250e51e399a29ab40f4678a",
    "dateISO": "2026-05-21T23:22:39-04:00",
    "subject": "Student quiz runner: gate Start button on start/end time window (#123)"
  },
  {
    "hash": "ecc9ea8ec9c88953ad8135551e849eb0e330f37c",
    "dateISO": "2026-05-21T20:40:04-04:00",
    "subject": "Student Presentations page: table layout matching teacher (#122)"
  },
  {
    "hash": "88a3fb287656d5b0fd021304247d90f3dabde0d2",
    "dateISO": "2026-05-21T20:29:36-04:00",
    "subject": "Teacher Assignments: replace Submissions column with inbox action (#121)"
  },
  {
    "hash": "d1cd0d217ff4227fe93084073a1d043cddff8828",
    "dateISO": "2026-05-21T20:20:57-04:00",
    "subject": "Student Quizzes: outlined \"Take quiz\" badge gated by start/end window (#120)"
  },
  {
    "hash": "7978b48c398c6d5cfe43d55a95a6f2200c0ef99f",
    "dateISO": "2026-05-21T20:00:03-04:00",
    "subject": "Group assignments: friendly \"not in a group\" warning instead of crash (#119)"
  },
  {
    "hash": "129b4d0d095759542aa9a9efd5b2bc86f39c89fe",
    "dateISO": "2026-05-21T19:46:29-04:00",
    "subject": "Assignment + quiz scheduling: start / end / until dates (#118)"
  },
  {
    "hash": "c61cab66607795539d77f27d41f55df0727cc22f",
    "dateISO": "2026-05-21T19:21:07-04:00",
    "subject": "Student Quizzes page: table layout matching teacher (#117)"
  },
  {
    "hash": "ffd8baaaaae4793f5994ddd56114b8958eb4aca2",
    "dateISO": "2026-05-21T19:15:53-04:00",
    "subject": "Quiz runner: MarkdownEditor for short_answer + case_analysis (#116)"
  },
  {
    "hash": "c0be0722d58ce824732741bc2712fc1dda2215a4",
    "dateISO": "2026-05-21T19:12:24-04:00",
    "subject": "Quiz runner: \"Answer:\" label above free-text textareas (#115)"
  },
  {
    "hash": "8a159638c8ce5589d72689f89e3d7003543777b5",
    "dateISO": "2026-05-21T19:02:10-04:00",
    "subject": "Quiz runner: pin timer, markdown prompts, textarea for short answer (#114)"
  },
  {
    "hash": "6de500591c5d5ca58f71ddb906c5d1ad0da041b4",
    "dateISO": "2026-05-21T18:09:53-04:00",
    "subject": "Student Assignments page: table layout matching teacher (#113)"
  },
  {
    "hash": "d086c8e1b2e88d154351fc92b883274de0a66a34",
    "dateISO": "2026-05-21T17:19:30-04:00",
    "subject": "Modules summary: h-8 chips + assignments first (#112)"
  },
  {
    "hash": "2448b1b52375a0dd7b6648a3dc183dbb1589b58a",
    "dateISO": "2026-05-21T17:10:10-04:00",
    "subject": "Modules: inline content-tally badges (outlined, with mini count) (#111)"
  },
  {
    "hash": "879f54c0e4355d3190f12dac767ce07a54b3f72c",
    "dateISO": "2026-05-21T16:56:32-04:00",
    "subject": "Student lists: show submission status + submitted date per assignment (#110)"
  },
  {
    "hash": "a64470b2b94753014a1c5878a28db546b4f858d3",
    "dateISO": "2026-05-21T14:55:40-04:00",
    "subject": "Grading: attendance + group weights share one 100% pool (#109)"
  },
  {
    "hash": "88fb839991ae647cd168d26a64ff20510a832705",
    "dateISO": "2026-05-21T14:34:48-04:00",
    "subject": "Students toolbar: half-size borderless copy icon (#108)"
  },
  {
    "hash": "c2bebcf278f87447634fc9b4dfe2ccb9ea2f17d4",
    "dateISO": "2026-05-21T14:25:11-04:00",
    "subject": "Student Students page: toolbar matches teacher + All filter (#107)"
  },
  {
    "hash": "f2df6abe69e5f2bdc04e3d9658938e7f19eca3f8",
    "dateISO": "2026-05-21T14:16:37-04:00",
    "subject": "Students toolbar: copy invite code with check-icon ack (#106)"
  },
  {
    "hash": "c6f6a128d149e39bea6c24ab79149ea3db807e9f",
    "dateISO": "2026-05-21T14:08:08-04:00",
    "subject": "Students toolbar: show active invitation code + days to expiry (#105)"
  },
  {
    "hash": "ec7b445196c0651fe14627492777ac42eedff3e0",
    "dateISO": "2026-05-21T13:56:37-04:00",
    "subject": "Students page: UserRoundPlus icon + per-row enrollment count (#104)"
  },
  {
    "hash": "184200e30a21a3f78db749525e93e1485b393a99",
    "dateISO": "2026-05-21T13:42:40-04:00",
    "subject": "Students toolbar: refresh-last, group chips right-aligned, icon \"+ New\" (#103)"
  },
  {
    "hash": "8afb413c532f816794a02ce8992681febf1f9a39",
    "dateISO": "2026-05-21T13:33:51-04:00",
    "subject": "Students page: roster table + group-set filters (#102)"
  },
  {
    "hash": "d4be99877c1548d5adc555692b1b34c61098280b",
    "dateISO": "2026-05-21T13:09:55-04:00",
    "subject": "ci: re-trigger after merge skipped CI"
  },
  {
    "hash": "271dc7e30f467a0e7761f777025bf64f05d5c9c6",
    "dateISO": "2026-05-21T13:09:12-04:00",
    "subject": "Student groups (PR2): assignment group submissions + per-member grades (#101)"
  },
  {
    "hash": "d05c0162f55ab74e0e48de59cc6cdaacf3f84f3b",
    "dateISO": "2026-05-21T12:44:37-04:00",
    "subject": "ci: re-trigger after merge skipped CI"
  },
  {
    "hash": "afd06d9b52ea6be768f04ded500eb12acb9b66cb",
    "dateISO": "2026-05-21T12:38:23-04:00",
    "subject": "Student groups (PR1): teacher CRUD + student self-signup (#100)"
  },
  {
    "hash": "02e511a374880877e47696816ff9f6006d872890",
    "dateISO": "2026-05-21T11:39:51-04:00",
    "subject": "FERPA §99.7(a): annual acknowledgment interstitial (#99)"
  },
  {
    "hash": "8ab2630d1fab4d1d1a7018b15d650be6ecd5798e",
    "dateISO": "2026-05-21T11:32:22-04:00",
    "subject": "FERPA hardening: R2 cleanup retry + HTTPS check (#98)"
  },
  {
    "hash": "3624f80cd82603678baad55d085cf842958b0ab8",
    "dateISO": "2026-05-21T11:26:32-04:00",
    "subject": "FERPA §99.20: record-correction-request workflow (#97)"
  },
  {
    "hash": "07e7e0ab6350d40a400c896d80411024cfe16f97",
    "dateISO": "2026-05-21T11:14:42-04:00",
    "subject": "FERPA: nightly retention sweep (#96)"
  },
  {
    "hash": "6c439ef706fd6649a9d768b81d46da8b92b8a44c",
    "dateISO": "2026-05-21T11:07:16-04:00",
    "subject": "FERPA hardening: redact contact PII + strip attendance IP from staff views (#95)"
  },
  {
    "hash": "b9c79b6a82cc6936137979c311170166a9fdaadd",
    "dateISO": "2026-05-21T10:54:17-04:00",
    "subject": "FERPA: GET /me/records/export — Download my records (#94)"
  },
  {
    "hash": "840bb6272ba1ce1a78e2ac41d6c5592e1cda3937",
    "dateISO": "2026-05-21T10:45:22-04:00",
    "subject": "FERPA: GET /me/records/disclosures + Settings disclosures page (#93)"
  },
  {
    "hash": "7474f4a7fe249dc145a7725fc13e493daf6276f7",
    "dateISO": "2026-05-21T10:24:25-04:00",
    "subject": "FERPA disclosure log foundation (audit_logs.disclosed_student_id) (#92)"
  },
  {
    "hash": "2f68fa562922f251b3ca193dc01968ebc47cf4ab",
    "dateISO": "2026-05-21T10:15:06-04:00",
    "subject": "FERPA prep: list Gamma subprocessor + harden CORS default (#91)"
  },
  {
    "hash": "c093b5b7e6418992d1bcd96cec4bfaf68bb2c794",
    "dateISO": "2026-05-21T09:21:15-04:00",
    "subject": "Session expiry warning dialog with countdown + auto-logout (#90)"
  },
  {
    "hash": "38550ed1a82945fb7d1198df20236f4a91bd87ea",
    "dateISO": "2026-05-21T00:26:36-04:00",
    "subject": "Canvas-style assignment groups (#89)"
  },
  {
    "hash": "5facf48cf2a0870fab7a0c7fbd852fa8b91d80a0",
    "dateISO": "2026-05-20T23:24:12-04:00",
    "subject": "Design: Canvas-style assignment groups (#88)"
  },
  {
    "hash": "fd0942e02140b531f90b9bf4bbee8e403cae58e7",
    "dateISO": "2026-05-20T19:01:06-04:00",
    "subject": "Resume polling stale Gamma jobs on page load (#87)"
  },
  {
    "hash": "f96e88f282f8bf8d238dbb9dd4e665d74f60d39c",
    "dateISO": "2026-05-20T18:19:40-04:00",
    "subject": "Gamma generate: include draft reading materials (#86)"
  },
  {
    "hash": "4ea30b2e35d062236a0d890ed1963b170e6d3156",
    "dateISO": "2026-05-20T17:44:04-04:00",
    "subject": "Invitation-code redemption for existing students (#85)"
  },
  {
    "hash": "6ba5b56da08adc7f809b3f0cfcb16c7e05805ac6",
    "dateISO": "2026-05-20T16:56:13-04:00",
    "subject": "Design: invitation-code redemption for existing students (#84)"
  },
  {
    "hash": "bb0c69a345ef8aed9546fbefcfa97da6180857c0",
    "dateISO": "2026-05-20T16:23:40-04:00",
    "subject": "Course hard-delete (Danger Zone) with FERPA audit + R2 cleanup (#83)"
  },
  {
    "hash": "a645e95bec3d1f1fb7d1e2718b98628ad5d0fd89",
    "dateISO": "2026-05-20T14:52:14-04:00",
    "subject": "Ignore .worktrees/ for local git worktrees"
  },
  {
    "hash": "51002f851e96ac7945dec02316b74da2783d41f1",
    "dateISO": "2026-05-20T14:46:42-04:00",
    "subject": "Design: course hard-delete (Danger Zone) (#82)"
  },
  {
    "hash": "c890c23e49cde65faf75fd6e91e4321e605beda6",
    "dateISO": "2026-05-20T14:28:21-04:00",
    "subject": "Legal: publish Privacy Policy v1.0 (#81)"
  },
  {
    "hash": "e6b95117ba232fd88184a5b33747c44f208fd3a0",
    "dateISO": "2026-05-20T10:40:59-04:00",
    "subject": "API: surface Cloudflare edge blocks as 503, not 500 (#80)"
  },
  {
    "hash": "333b3bcc0587f299f835df346fac2b5f297ef64c",
    "dateISO": "2026-05-20T10:35:09-04:00",
    "subject": "Grading: compact student panel + wide detail pane (#79)"
  },
  {
    "hash": "d6bc57d4c4e763ee72740fe6700cc0504b7cf591",
    "dateISO": "2026-05-20T10:28:33-04:00",
    "subject": "Gamma: generate from a dedicated page instead of a dialog (#78)"
  },
  {
    "hash": "d9d5af3d94dec8e2fba8ed00206d629ae522564e",
    "dateISO": "2026-05-20T10:16:14-04:00",
    "subject": "Gradebook: per-student detail page with per-part edits (#77)"
  },
  {
    "hash": "016353662c561c5d79fb5f9d89dd78fb790f7a7f",
    "dateISO": "2026-05-20T09:44:15-04:00",
    "subject": "Attendance: per-session late + close-self-sign thresholds (#76)"
  },
  {
    "hash": "c5f38e266676cd7850191c3af3fac5becdce9754",
    "dateISO": "2026-05-20T09:32:03-04:00",
    "subject": "Student self-sign attendance with IP capture (#75)"
  },
  {
    "hash": "f224406f2762e1e4924eb0d12fe9852164f05b7d",
    "dateISO": "2026-05-20T09:14:53-04:00",
    "subject": "Student modules: items are now plain links to dedicated pages (#74)"
  },
  {
    "hash": "f02ff500b0513d9374640c277ab15009ece819f9",
    "dateISO": "2026-05-20T09:05:08-04:00",
    "subject": "Modules page: per-type content counts beside module title (#73)"
  },
  {
    "hash": "289425dfcabe401cb28f4c5e895eb6355bc65551",
    "dateISO": "2026-05-20T08:47:18-04:00",
    "subject": "Extend user session timeout from 15 minutes to 12 hours (#72)"
  },
  {
    "hash": "4a157dc3eeeb48e38f28b120303bc1b4edfce017",
    "dateISO": "2026-05-20T04:06:35-04:00",
    "subject": "Teachers can generate student invitation codes for their courses (#71)"
  },
  {
    "hash": "a5fba3f59b1cfad74a0994eef71cac0395b1c7aa",
    "dateISO": "2026-05-20T03:54:54-04:00",
    "subject": "New-course form: surface course-code rules instead of generic toast (#70)"
  },
  {
    "hash": "1adc7c614b074d3e8dad4eda06343df3465f95d7",
    "dateISO": "2026-05-20T03:41:56-04:00",
    "subject": "Teacher invitations: use Cloudflare Email Service (beta) sender (#69)"
  },
  {
    "hash": "3d3db7e7ae8f1dd642adc367590a29b4193d8229",
    "dateISO": "2026-05-20T03:31:57-04:00",
    "subject": "Teacher invitations: swap Resend for Cloudflare send_email binding (#68)"
  },
  {
    "hash": "68b1be9f83b1989176b58a5661f17588fbffafab",
    "dateISO": "2026-05-20T03:22:56-04:00",
    "subject": "Teacher invitations: send a professional email via Resend (#67)"
  },
  {
    "hash": "803b90d714e76ab5ed74a4a8769df2b9ecc38642",
    "dateISO": "2026-05-20T03:07:47-04:00",
    "subject": "deploy: inject GIT_SHA + BUILT_AT into Worker deploy (#66)"
  },
  {
    "hash": "9aa5f57ae57be4edf462248ceddc623983eb1f35",
    "dateISO": "2026-05-20T02:57:20-04:00",
    "subject": "Point production config at fsuac.com (web) + api.fsuac.com (API) (#65)"
  },
  {
    "hash": "0e91e3584cebc1367476a41e8a714b6c2ea33133",
    "dateISO": "2026-05-20T02:45:30-04:00",
    "subject": "Student modules page: inline content + reply/submit (#64)"
  },
  {
    "hash": "75410f80b45fa2b85cdf2881efde00570a8ba355",
    "dateISO": "2026-05-20T02:29:37-04:00",
    "subject": "Discussion: table layout + module linking, list under modules (#63)"
  },
  {
    "hash": "81098f2be4622079fdc9dd8079c71dd84ca916fc",
    "dateISO": "2026-05-20T02:15:12-04:00",
    "subject": "Modules page: list linked quizzes as a section (#62)"
  },
  {
    "hash": "164b27a9806de044172d1444f5beae664859f12e",
    "dateISO": "2026-05-20T01:55:25-04:00",
    "subject": "Teacher quizzes: switch to table design (#61)"
  },
  {
    "hash": "76f3c706938776a07c57b7f538a55998ab2a3132",
    "dateISO": "2026-05-20T01:37:39-04:00",
    "subject": "Fix assignments edit button + swap to SquarePen icon (#60)"
  },
  {
    "hash": "c2461a888c2a52057089925d636b468a61c45da2",
    "dateISO": "2026-05-20T01:30:12-04:00",
    "subject": "Assignments table: add explicit Edit action button (#59)"
  },
  {
    "hash": "291ffb36a43d3a953b8df3e38b118885f7fbc865",
    "dateISO": "2026-05-20T01:16:46-04:00",
    "subject": "Modules page: list linked assignments as a section (#58)"
  },
  {
    "hash": "0a16bdf70fbb1e56d19013f49a5a62ab2450c297",
    "dateISO": "2026-05-20T00:58:08-04:00",
    "subject": "Teacher assignments: switch to table design, mirror presentations (#57)"
  },
  {
    "hash": "0cbc958c43004a67375e9ad65dc5b690b4e977dc",
    "dateISO": "2026-05-20T00:30:32-04:00",
    "subject": "SideNav: move Modules next to Overview in teacher course nav (#56)"
  },
  {
    "hash": "71910cf1c0dcbd07c56d016a04ac767cee8fab23",
    "dateISO": "2026-05-20T00:20:40-04:00",
    "subject": "Modules page: list linked presentations as a section (#55)"
  },
  {
    "hash": "a0b416853fbd3dbfd2e2e33459d627826f15239d",
    "dateISO": "2026-05-20T00:09:44-04:00",
    "subject": "Status indicator: match action-button visual (#54)"
  },
  {
    "hash": "7848b8cf34905be25fa2077a29635b9b9f5c0d5e",
    "dateISO": "2026-05-20T00:04:58-04:00",
    "subject": "Presentations table: add Module column, status as title icon (#53)"
  },
  {
    "hash": "7ff081fc4c299c36419a3b23fc97e20b0a0571ce",
    "dateISO": "2026-05-19T23:56:45-04:00",
    "subject": "Presentations table: confirm delete, drop edit icon, add move-to-module (#52)"
  },
  {
    "hash": "9773a43e78a9c2e3cdb9fbfb03091777d573beee",
    "dateISO": "2026-05-19T23:46:59-04:00",
    "subject": "Teacher presentations: attach table top nav, drop New button (#51)"
  },
  {
    "hash": "02b4fa3af560476690b12b2b2429aaa62585b025",
    "dateISO": "2026-05-19T23:38:18-04:00",
    "subject": "Teacher presentations: switch from card grid to table (#50)"
  },
  {
    "hash": "27b1124c35ee4e2d4c8dd663ae4833abcdef2ee4",
    "dateISO": "2026-05-19T23:27:32-04:00",
    "subject": "Gamma slide count: fall back to requested numCards (#49)"
  },
  {
    "hash": "47d22e18ff2b9e6695fe5d1cfe1a326cf544b1d4",
    "dateISO": "2026-05-19T23:20:04-04:00",
    "subject": "Remove Share button from teacher presentation card (#48)"
  },
  {
    "hash": "0915d7635d64d4611ca1b2c68101415f2b547007",
    "dateISO": "2026-05-19T23:02:06-04:00",
    "subject": "Gamma dialog: image style dropdown, remove Pearl fallback (#47)"
  },
  {
    "hash": "952cde895c2d16aebe8a14e6b13b657c98da2d18",
    "dateISO": "2026-05-19T22:48:03-04:00",
    "subject": "Gamma dialog: pin Pearl theme + add document type dropdown (#46)"
  },
  {
    "hash": "f822d1e89fd779b213791269bb09ab9cd1b86eeb",
    "dateISO": "2026-05-19T22:33:59-04:00",
    "subject": "Fix Gamma themes dropdown: parse `data` field (#45)"
  },
  {
    "hash": "a5876cc4dbd9f7601621f1aae8e5f71aaa772ea8",
    "dateISO": "2026-05-19T20:38:32-04:00",
    "subject": "Gamma generation progress bar + public share viewer (#44)"
  },
  {
    "hash": "214442c630d606572d203597e796771c88eac73c",
    "dateISO": "2026-05-19T20:06:26-04:00",
    "subject": "Register migration 0010 in journal and split statements (#43)"
  },
  {
    "hash": "21eb408a55f8ffdbaf0f69c1d5a148880ac63889",
    "dateISO": "2026-05-19T19:52:14-04:00",
    "subject": "Fix Gamma 500: neon-http has no db.transaction (#42)"
  },
  {
    "hash": "ec63860d7d2f482f722f8c65fa821c365255ca17",
    "dateISO": "2026-05-19T19:44:40-04:00",
    "subject": "Fix Gamma 400 + add textMode and numCards to generate dialog (#41)"
  },
  {
    "hash": "6394f77aa81cd0f7f89f730d27f1e36cc4ffa1a0",
    "dateISO": "2026-05-19T14:21:29-04:00",
    "subject": "Generate presentations from reading materials with Gamma (#40)"
  },
  {
    "hash": "9e18536ca679104189d83b050c2e15f540fd2b11",
    "dateISO": "2026-05-19T11:51:26-04:00",
    "subject": "Files: single-call multipart upload via R2 binding (#39)"
  },
  {
    "hash": "02d493a33b660b07f4a4f0efde089ca2c0660bfb",
    "dateISO": "2026-05-19T11:18:06-04:00",
    "subject": "R2 storage: one-command setup + clearer error (#38)"
  },
  {
    "hash": "77309aea5e7d1abeb173ec93983fbf014b615fd4",
    "dateISO": "2026-05-19T10:14:23-04:00",
    "subject": "Replace edit-material dialog with a dedicated page (#37)"
  },
  {
    "hash": "5fb5c408948ddc7eb98303d423257cc33aaa39fd",
    "dateISO": "2026-05-19T09:56:25-04:00",
    "subject": "Click reading-material row on Modules page to open detail view (#36)"
  },
  {
    "hash": "dbaef3811fda0f5619410fdf2eb8a2735ed819a2",
    "dateISO": "2026-05-19T08:33:39-04:00",
    "subject": "Edit-material dialog: full-page width, no backdrop dismiss (#35)"
  },
  {
    "hash": "5e00893ebf772addef899c8cc85f82c59dec14f1",
    "dateISO": "2026-05-19T08:22:12-04:00",
    "subject": "Replace window.confirm with rich delete dialog on TeacherMaterialsPage (#34)"
  },
  {
    "hash": "b49d60f71722190e54fe815e236bb412d336f35f",
    "dateISO": "2026-05-19T07:47:48-04:00",
    "subject": "Public site redesign + FERPA/legal pages (#33)"
  },
  {
    "hash": "ae18b5dddeeafa4937e60d5363489b5f45d60e2a",
    "dateISO": "2026-05-19T02:38:41-04:00",
    "subject": "Editable prompt templates for AI generation (#32)"
  },
  {
    "hash": "79b49bfc84cebcfe17e38aaf8d31c7c1cc1f38a5",
    "dateISO": "2026-05-19T01:19:42-04:00",
    "subject": "fix(i18n): resolve zh-CN correctly when switching language (#31)"
  },
  {
    "hash": "c1047d219abad1c3d77f22379bab9e7bffc3b589",
    "dateISO": "2026-05-19T01:11:11-04:00",
    "subject": "Show per-1M-token price in model dropdown (#30)"
  },
  {
    "hash": "3799482574e030aecabb60ffb16c7c97fa941b89",
    "dateISO": "2026-05-19T01:07:24-04:00",
    "subject": "feat(i18n): add language switcher to top nav (#29)"
  },
  {
    "hash": "e26adf5fec697305a77e03f5c6c17b46e90a6893",
    "dateISO": "2026-05-19T01:00:45-04:00",
    "subject": "Realtime agent output for AI generation jobs (#28)"
  },
  {
    "hash": "62f44067375190bc98051fcfc6a5256b1225e385",
    "dateISO": "2026-05-18T23:21:54-04:00",
    "subject": "Support Cloudflare AI Gateway Authenticated mode (#27)"
  },
  {
    "hash": "e5c023775964ca6d731ee7bccbf66ba6ce3a4c97",
    "dateISO": "2026-05-18T20:48:43-04:00",
    "subject": "AI content generator — Phase 2 reading material generation (#26)"
  },
  {
    "hash": "5014f2fd2c79b7b032437272d932e7f51047b1f8",
    "dateISO": "2026-05-18T20:23:23-04:00",
    "subject": "Replace Model ID input with a provider-scoped dropdown (#25)"
  },
  {
    "hash": "66e22b9840f228983dcedfde1500072decb91ca1",
    "dateISO": "2026-05-18T20:11:09-04:00",
    "subject": "AI content generator — Phase 1 foundation (#24)"
  },
  {
    "hash": "6b668e60e5fa66b0d05c5aff4276a408f754cb41",
    "dateISO": "2026-05-18T18:47:40-04:00",
    "subject": "Add teacher course overview page; move settings to Manage section (#23)"
  },
  {
    "hash": "aa8ed006047e0f4624ebce3987935645d6af9309",
    "dateISO": "2026-05-18T18:35:05-04:00",
    "subject": "Display teacher modules in an accordion (#22)"
  },
  {
    "hash": "90c8315a22af5b3fba9e5e586ffd15ea8ef2dca4",
    "dateISO": "2026-05-18T17:42:15-04:00",
    "subject": "ci: wire pnpm db:migrate into deploy workflow (COU-19) (#21)"
  },
  {
    "hash": "58b90162085202da4950d710427fd490612f3321",
    "dateISO": "2026-05-18T17:25:07-04:00",
    "subject": "Admin can invite users as teachers (COU-16) (#18)"
  },
  {
    "hash": "db3600a356963f4aea645611b5a5049c4f6950df",
    "dateISO": "2026-05-18T17:19:48-04:00",
    "subject": "Restyle course row actions as colored Lucide icon badges (COU-18) (#20)"
  },
  {
    "hash": "c25664ea5e9337aec85bdaab0671efadd201fcad",
    "dateISO": "2026-05-18T16:59:51-04:00",
    "subject": "API auth hardening + self-serve API token UI (COU-17) (#19)"
  },
  {
    "hash": "471701a2453e86dc19f49e677bab60d26c95b223",
    "dateISO": "2026-05-18T16:55:32-04:00",
    "subject": "Markdown editor + view for long-form content fields (COU-15) (#17)"
  },
  {
    "hash": "4101b72de567c9d22cc06ee55147f704dde927a3",
    "dateISO": "2026-05-18T16:28:25-04:00",
    "subject": "Reading materials: module-scoped listing, full edit, sourceType switching (COU-13) (#16)"
  },
  {
    "hash": "c1f96c95d881edfa7eaafbd4a72ec894a8d773bb",
    "dateISO": "2026-05-18T16:25:33-04:00",
    "subject": "Group course side menu items into labeled sections (COU-14) (#15)"
  },
  {
    "hash": "8ffb09a6c1501c227e890f30cae6d8f92d7b333a",
    "dateISO": "2026-05-18T15:41:01-04:00",
    "subject": "Remove max-w-7xl cap on role-scoped layout container (COU-12) (#14)"
  },
  {
    "hash": "b32018b1a56db65e879b179e72d7fcd788cbc3a5",
    "dateISO": "2026-05-18T15:24:45-04:00",
    "subject": "Make /dashboard the canonical dashboard URL for all roles (COU-11) (#13)"
  },
  {
    "hash": "db965342c4d7d7bbe478d880e66c577d48ad65aa",
    "dateISO": "2026-05-18T15:03:16-04:00",
    "subject": "Home button routes to dashboard for all roles (COU-11) (#12)"
  },
  {
    "hash": "544ab430520eadc3d62900c133087cebb763754e",
    "dateISO": "2026-05-18T14:48:46-04:00",
    "subject": "Remove duplicate in-page course sidebar, add Home button in top nav (COU-11) (#11)"
  },
  {
    "hash": "9fc78592f3f5cc90a4cbc0243295b3686e3923c3",
    "dateISO": "2026-05-18T14:27:55-04:00",
    "subject": "Restore full role-level items in global SideNav on course routes (COU-11) (#10)"
  },
  {
    "hash": "569e348402d3a172185b560781a15c72c11c356c",
    "dateISO": "2026-05-18T13:42:36-04:00",
    "subject": "Add course-scoped side menu on course detail pages (COU-10) (#9)"
  },
  {
    "hash": "4165d676c3054a2b5eb22d885441c892890575d0",
    "dateISO": "2026-05-18T13:14:33-04:00",
    "subject": "Switch back-office top nav to collapsible side menu (#8)"
  },
  {
    "hash": "4c905cbe70d52b1680ff09ed47b0ec366b10b6d0",
    "dateISO": "2026-05-18T12:04:53-04:00",
    "subject": "M6 — Fix Pages deploy job (#7)"
  },
  {
    "hash": "003d354dd7ad2ad88acf29cf203234ca1697c037",
    "dateISO": "2026-05-18T12:00:40-04:00",
    "subject": "M6 — Deploy · CI/CD · README · OpenAPI / API Docs (#6)"
  },
  {
    "hash": "5bd8fb334fb1e3dfa335afb24ac30198e30e0bda",
    "dateISO": "2026-05-18T10:58:10-04:00",
    "subject": "M5 — Grading policy, final grades, alerts, dashboards (#5)"
  },
  {
    "hash": "84b18584b40c86391b228dd3210d8f59b2da9de4",
    "dateISO": "2026-05-18T09:13:54-04:00",
    "subject": "M4 — Assessment (Quizzes · Attendance) (#4)"
  },
  {
    "hash": "311e0bf12a1c49e427a32174f91b461cb4d8a666",
    "dateISO": "2026-05-18T08:45:38-04:00",
    "subject": "M3 — Teaching content: presentations, assignments, discussions (#3)"
  },
  {
    "hash": "43955c8d1438e3db95d6f0ab238e62f4c929799b",
    "dateISO": "2026-05-18T02:01:32-04:00",
    "subject": "M2 — Course core: courses, modules, enrollments, invitations, materials, R2 (#2)"
  },
  {
    "hash": "7735849aae875db82a806e86bc7f59aba04cba34",
    "dateISO": "2026-05-18T01:07:55-04:00",
    "subject": "M1 — Database schema, JWT + API token auth (#1)"
  }
];
