import { Link } from 'react-router-dom';
import { LegalPageHeader } from '@/components/legal/LegalPageHeader';

export function TermsPage(): JSX.Element {
  return (
    <>
      <LegalPageHeader
        title="Terms of Service"
        summary="The agreement between [COMPANY LEGAL NAME] and the people and institutions that use CourseWise."
        lastUpdated="2026-05-19"
        version="v0.1-draft"
      />

      <h2>Acceptance</h2>
      <p>
        These Terms govern your use of the CourseWise platform, including the
        marketing site at the CourseWise domain, the web application, and any
        APIs we provide (collectively, the "Service"). By creating an account,
        signing an order form, or otherwise using the Service, you agree to
        these Terms. If you are accepting on behalf of an institution, you
        represent that you have authority to bind that institution. Where a
        signed master services agreement, data processing agreement, or
        institutional order form exists between [COMPANY LEGAL NAME] and an
        institution, that agreement controls in the event of conflict; these
        Terms fill the gaps.
      </p>

      <h2>Accounts</h2>
      <p>
        Most teacher and student accounts on CourseWise are provisioned by an
        institution. The institution is responsible for keeping its roster
        accurate, for assigning the correct role to each user, and for
        offboarding users who no longer need access. Individuals are
        responsible for keeping their credentials confidential and for
        notifying the institution and us promptly if they suspect their
        account has been used without authorization.
      </p>
      <p>
        Some teachers may sign up directly for a personal evaluation account.
        Personal accounts are intended for evaluation and lesson preparation;
        they are not intended to be used to administer instruction to a full
        class of identified students without an institutional contract in
        place.
      </p>

      <h2>Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>
          Use the Service to violate any law or any third party's rights,
          including intellectual property and privacy rights.
        </li>
        <li>
          Upload material that you do not have the right to use, or that you
          know to be defamatory, harassing, or unlawful.
        </li>
        <li>
          Attempt to bypass authentication, scrape data you are not entitled
          to, probe the Service for vulnerabilities outside our published
          responsible-disclosure process, or interfere with other users.
        </li>
        <li>
          Use the Service to make decisions that have legal or similarly
          significant effects on a student (such as expulsion or denial of a
          diploma) without meaningful human review.
        </li>
        <li>
          Use the Service to build a competing product, or to train a separate
          AI model on data the Service generates.
        </li>
      </ul>
      <p>
        Our published responsible-disclosure policy is at{' '}
        <Link to="/legal/responsible-disclosure">/legal/responsible-disclosure</Link>{' '}
        and describes how to report a security issue safely.
      </p>

      <h2>School as controller</h2>
      <p>
        For accounts provisioned by [INSTITUTION NAME], the institution is the
        controller of the personal information of its students and staff that
        flows through the Service. [COMPANY LEGAL NAME] processes that
        information as the institution's service provider, on the
        institution's documented instructions, and only for the purposes set
        out in the agreement. The institution remains responsible for
        obtaining any consents or making any disclosures required of it by
        FERPA, COPPA, state student-privacy law, or other applicable law in
        connection with its use of the Service.
      </p>

      <h2>Intellectual property</h2>
      <p>
        The Service, including its software, user interface, design,
        documentation, and trademarks, is owned by [COMPANY LEGAL NAME] and
        its licensors. Subject to these Terms, we grant the institution and
        its users a limited, non-exclusive, non-transferable right to access
        and use the Service during the term of the agreement.
      </p>
      <p>
        Content uploaded or generated by users (for example, reading material
        a teacher writes, a question a teacher edits, a student response) is
        owned by the institution or the individual user, as the case may be,
        under the institution's own policies. We do not claim ownership of
        that content. We need a limited license to host, copy, transmit, and
        display it so that we can provide the Service, and to use it
        internally to operate, secure, debug, and improve the Service in
        aggregated or de-identified form.
      </p>
      <p>
        AI-generated output produced by the Service in response to a prompt is
        provided to the institution and the user for their use. Because AI
        output can be wrong, biased, or unsuitable in context, you are
        responsible for reviewing it before relying on it for instructional or
        grading decisions.
      </p>

      <h2>Fees</h2>
      <p>
        Fees, billing frequency, and payment terms are set in the order form
        between [COMPANY LEGAL NAME] and [INSTITUTION NAME]. Unless that order
        form says otherwise, fees are quoted in United States dollars, are due
        net thirty days from the invoice date, and are non-refundable. We may
        revise list pricing on renewal with prior written notice. Personal
        evaluation accounts are offered free of charge and may be discontinued
        at our discretion.
      </p>

      <h2>Termination</h2>
      <p>
        Institutional subscriptions terminate at the end of their stated term
        unless renewed. Either party may terminate the agreement for the
        other's material breach, including non-payment, if the breach is not
        cured within thirty days of written notice. Either party may
        terminate immediately if the other becomes insolvent, files for
        bankruptcy, or ceases ordinary business operations.
      </p>
      <p>
        On termination, [COMPANY LEGAL NAME] will make institutional data
        available for export for the period set in the agreement (typically
        thirty days) and will then delete it as described in our{' '}
        <Link to="/legal/privacy">Privacy Policy</Link>. Sections of these
        Terms that by their nature should survive termination (intellectual
        property, fees accrued before termination, disclaimers, limitations of
        liability, governing law) survive.
      </p>

      <h2>Disclaimers</h2>
      <p>
        The Service is provided on an "as is" and "as available" basis. We do
        not warrant that the Service will be uninterrupted, error-free, or
        free of harmful components, and we do not warrant the accuracy of
        AI-generated output. To the maximum extent permitted by law, we
        disclaim implied warranties of merchantability, fitness for a
        particular purpose, and non-infringement.
      </p>
      <p>
        Our aggregate liability under these Terms is limited to the fees paid
        or payable by the institution for the Service in the twelve months
        immediately preceding the event giving rise to the claim. Neither
        party is liable for indirect, incidental, special, consequential, or
        punitive damages. Nothing in these Terms limits liability that cannot
        be limited under applicable law (for example, fraud or willful
        misconduct).
      </p>

      <h2>Governing law</h2>
      <p>
        These Terms are governed by the laws of the State of [STATE], United
        States, without regard to its conflict-of-laws principles. The state
        and federal courts located in [STATE] have exclusive jurisdiction over
        disputes, except that either party may seek injunctive relief in any
        court of competent jurisdiction to protect its intellectual property
        or confidential information. Where a public-sector institution's
        applicable law requires a different venue, choice of law, or
        sovereign-immunity treatment, the institution's order form will
        control.
      </p>

      <h2>Contact</h2>
      <p>
        For questions about these Terms, contract requests, or to report a
        concern, please use our{' '}
        <Link to="/legal/data-requests">Data Requests page</Link>. Notices
        required to be in writing under these Terms should be sent to the
        address shown there.
      </p>
    </>
  );
}
